# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing
VAGRANTFILE_API_VERSION = '2'

PM_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))
PM_CONFIG = File.expand_path(File.join(File.dirname(__FILE__), 'config.json'))
require_relative File.join(PM_ROOT, 'lib', 'ruby', 'playa_settings')
pmconf = PlayaSettings.new(PM_CONFIG)

# #############################################################################
# Vagrant VM Definitions
# #############################################################################

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb, override|
    vb.name = pmconf.box_name

    # Every Vagrant virtual environment requires a box to build off of.
    override.vm.box = pmconf.box_name

    # Vagrant only retrieves box images from vm.box_url if it does not have a
    # local copy in ~/.vagrant.d/boxes/$BOX_NAME. These can be removed with the
    # command: "vagrant box remove $BOX_NAME"
    override.vm.box_url = pmconf.box_url

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    override.vm.network :private_network, ip: pmconf.ip_address

    # If true, then any SSH connections made will enable agent forwarding.
    # Default value: false
    override.ssh.forward_agent = true

    # Note: You'll want a decent amount of memory for your mesos master/slave
    # VM. The strict minimum, at least while the VM is provisioned, is the
    # amount necessary to compile mesos and the jenkins plugin. 2048m+ is
    # recommended.  The CPU count can be lowered, but you may run into issues
    # running the Jenkins Mesos Framework if you do so.
    vb.customize ['modifyvm', :id, '--memory', pmconf.vm_ram]
    vb.customize ['modifyvm', :id, '--cpus',   pmconf.vm_cpus]

    # Make the project root (and ansible code) available to the guest VM.
    # This allows us to provision directly inside the VM using ansible and
    # removes the requirement of having ansible installed on the host.
    config.vm.synced_folder "../../", "/vagrant"

    config.vm.provision :shell do |shell|
      shell.path = "../../ansible/bootstrap.sh"
    end

  end

end
